---
abstract: 'Make constructor functions faster by trading space for time'
author:
  - 'Kenta Sato, C<< <kenta.sato.1990 at gmail.com> >>'
  - 'Kenta Sato <kenta.sato.1990@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Memoize-Class-Constructor
no_index:
  directory:
    - inc
    - t
requires:
  Data::MessagePack: 0
  Sub::Install: 0
  common::sense: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.001000
